# 1) Base
FROM node:22-alpine

WORKDIR /app

# 2) Copiamos workspace y lockfile
COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./

# 3) Copiamos package.json y tsconfig del gateway
COPY api-gateway/package.json api-gateway/tsconfig.json ./api-gateway/

# 4) Instalamos pnpm y dependencias de todos los workspaces
RUN npm install -g pnpm
RUN npm install -g pnpm \
 && npm install -g @nestjs/cli

# 5) Copiamos el resto del código de api-gateway
COPY api-gateway/ ./api-gateway/

# 6) Entramos al subdirectorio del gateway
WORKDIR /app/api-gateway


# 6.2) Compilamos con Nest
RUN pnpm install --filter "api-gateway" --save-dev @nestjs/cli
RUN pnpm build

# 7) Exponemos el puerto (ej.: 3003)
EXPOSE 3000

# 8) Arrancamos modo producción
#   
CMD ["nest", "start", "--watch"]