packages:
  - api-gateway
  - auth-service
  - catalog-service
  - user-service

ignoredBuiltDependencies:
  - '@scarf/scarf'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
