FROM node:22-alpine

# 1) Definimos el WORKDIR dentro del contenedor
WORKDIR /app

# 2) Copiamos solo lo necesario para instalar dependencias (evitar recargar capa)
#    Importante: el contexto de build será la raíz del monorepo,
#    pero aquí vamos a copiar los package.json del catálogo y del workspace.
COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./

# 3) Copiamos el package.json específico de user-service
COPY user-service/package.json user-service/tsconfig.json ./user-service/

# 4) Instalar pnpm y dependencias

# Ahora instalamos todos los workspaces (incluye user-service)
RUN npm install -g pnpm \
 && npm install -g @nestjs/cli
RUN pnpm install --frozen-lockfile --filter "user-service"

# 5) Copiamos el resto del código de user-service
COPY user-service/ ./user-service/

# 6) Generar Prisma Client y compilar TypeScript dentro del subdirectorio
WORKDIR /app/user-service
#RUN pnpm prisma generate

RUN pnpm install --filter "user-service" --save-dev @nestjs/cli
RUN pnpm build

# 7) Exponer puerto 
EXPOSE 3003

# 8) Comando final:
#    Primero aplicamos migraciones (deploy), luego levantamos la app en modo producción
CMD ["nest", "start", "--watch"]